### ISSUE TITLE
OS & App variable references still use DEVICE_NAME

### ISSUE THREAD

**Issue by someoneelsehere** [freyta/7Eleven-Python#14]
Looks like the OS_VERSION & APP_VERSION variables need fixing:

API_KEY = os.getenv('API_KEY',settings.API_KEY)
BASE_URL = os.getenv('BASE_URL',settings.BASE_URL)
PRICE_URL = os.getenv('PRICE_URL',settings.PRICE_URL)
DEVICE_NAME = os.getenv('DEVICE_NAME', settings.DEVICE_NAME)
OS_VERSION = os.getenv('**DEVICE_NAME**', settings.OS_VERSION)
APP_VERSION = os.getenv('**DEVICE_NAME**', settings.APP_VERSION)

**Comment by MattKobayashi** [comment]
I've submitted pull request #15 to fix this.
