### ISSUE TITLE
App is slow to load

### ISSUE THREAD

**Issue by MattKobayashi** [freyta/7Eleven-Python#16]
Seeing some very odd behaviour in the last 24 hours. The app is now really slow to load and frequently times out. I've tried reverting recent patches to see if that was causing the issue but I have been unsuccessful.

**Comment by MattKobayashi** [comment]
Nevermind, found the problem. Turned out to be my Docker trying to use IPv6 despite it not being configured on my network.

**Comment by freyta** [comment]
Hey mate.

Sometimes it is also slow because the 7Eleven servers are slow to respond. You can verify this by also checking with the app on your phone.
