### ISSUE TITLE
Oops, error: An unknown error occurred. Please try again later

### ISSUE THREAD

**Issue by poida97** [freyta/7Eleven-Python#18]
Hi Freighter, 
The script worked fine yesterday, however today I receive the following error when trying to log in:
```
Oops, error:
An unknown error occurred. Please try again later
```
I am able to log in fine using the current official app version.
Is there any way that I can get logs from the Python app?
thanks.

**Comment by ghost** [comment]
I am experiencing the same problem. Have attempted changing the IP, Device Name, OS Version, App Version.

**Comment by freyta** [comment]
Hey.

Yep it seems they have changed more stuff around with the 1.7.1 update than I thought. They've updated the key and key2 in the TSSA generating part, and also changed the first part of the string.

I.e. key is now `24, 167, 227, 147, 100, 31, 252, 42, 252, 192, 145, 122, 60, 70, 236, 201, 0, 133, 218, 161, 182, 244, 236, 205, 8, 211, 118, 51, 182, 76, 251, 32`

and 

key2 is `92, 105, 129, 237, 183, 87, 69, 31, 125, 142, 55, 240, 104, 196, 79, 157, 78, 91, 134, 181, 106, 6, 235, 105, 14, 41, 160, 127, 14, 87, 57, 156, 1, 47, 226, 250, 24, 45, 77, 114, 109, 224, 26, 37`.

I'll have a look into it more later today.

**Comment by alvinnguyen** [comment]
Let me know if you need some help on this.

**Comment by dumdumdummy** [comment]
Is there a quick fix that I can do on my end to make it work?

**Comment by NGPriest** [comment]
@alvinnguyen Time to make a PR? :p

**Comment by alvinnguyen** [comment]
@NGPriest  Happy to if I can for the sake of my life work out how this key works 🤔

I wish I have enough time to sniff the official app request and get more understanding of this.

**Comment by freyta** [comment]
So far I've managed to generate the correct signature part, but it isn't working for some reason. If you look at the APK I've reconstructed/ported the "new tssa" generating part of the code found in au.com.seveneleven.y.g. Here's what I made so far:

```
# Found in au.com.seveneleven.y.h - hard coded for now
encryption_key = base64.b64decode("g2JZ9nYmS3EhNiVTWyG5xbqGsqq4QFiNi6GLLbVhRbw=")

def generateTssa(URL, method, payload = None, accessToken = None):

    # Replace the https URL with a http one and convert the URL to lowercase
    URL       = URL.replace("https", "http").lower()
    # Get a timestamp and a UUID
    timestamp = int(time.time())
    uuidVar   = str(uuid.uuid4())
    # Join the variables into 1 string
    str3      = "yvktroj08t9jltr3ze0isf7r4wygb39s" + method + URL + str(timestamp) + uuidVar + payload
    # If we have a payload to encrypt, then we encrypt it and add it to str3
    if(payload):
        payload = base64.b64encode(hashlib.md5(payload).digest())
        str3   += payload
    signature = base64.b64encode(hmac.new(encryption_key, str3, digestmod=hashlib.sha256).digest())
    # Finish building the tssa string
    tssa = "tssa yvktroj08t9jltr3ze0isf7r4wygb39s:" + signature + ":" + uuidVar + ":" + str(timestamp)
    print tssa
    # If we have an access token append it to the tssa string
    if(accessToken):
        tssa += ":" + accessToken

    return tssa
```

At the moment I'm just trying to make GET requests work, then I'll make the POST ones work after.
Note: They have reordered how the TSSA is generated, it's now `GET/POST + URL + UUID + TIMESTAMP` compared to the old way which was `"GET/POST" + URL + TIMESTAMP + UUID`

**Comment by freyta** [comment]
Update:

Code works, I'll push an update for you guys tomorrow. Actually, I'm just an idiot, the above code works fine if you want to replace that in your app.py or init file.


Paging @alvinnguyen @NGPriest @dumdumdummy

**Comment by NGPriest** [comment]
@freyta Want me to write the PR?

**Comment by micyew** [comment]
Works after copy/paste above code to app.py....there is  an error in the below statement:

str3      = "yvktroj08t9jltr3ze0isf7r4wygb39s" + method + URL + str(timestamp) + uuidVar + payload

should be like this (without the payload keywrod at the end). Coz' you can't concatenate a NoneType obj if the payload is "none::
str3      = "yvktroj08t9jltr3ze0isf7r4wygb39s" + method + URL + str(timestamp) + uuidVar

**Comment by MattKobayashi** [comment]
I've tested the code from @freyta and @micyew above and it's working. PR #20 is the tested code running on my Docker container.

**Comment by poida97** [comment]
Great job again guys, works great.

**Comment by ghost** [comment]
Thank you team!
