### ISSUE TITLE
Can the Dockerfile reference python:2-alpine instead?

### ISSUE THREAD

**Issue by charleszlu** [freyta/7Eleven-Python#19]
The current docker image built using the base image of **python:2** results in a 921 MB image. If **python:2-alpine** can be used it would mean a significantly smaller image size (~100 MB).

**Comment by jitesh88** [comment]
definitely a good idea, raise a PR along with your issue if you've tested this locally.

i ran it on my server and it seem to start just fine. waiting for the authorisation token fix before confirming it works.

**Comment by MattKobayashi** [comment]
Tested working, thanks for the suggestion @charleszlu. I've submitted a pull request, but in the meantime if you want the image from Docker Hub feel free to pull mine: https://hub.docker.com/r/ingenieurmt/fuellock

**Comment by charleszlu** [comment]
@ingenieurmt Yes I've been using your docker image from the docker hub. Thanks for updating it. I can also confirm it works well. The size is only 75 MB now which is nice.

**Comment by micyew** [comment]
@charleszlu, @ingenieurmt Quite new to this docker thingy.....A quick step will be good....Is it something like this?
1.  install docker ce in a Ubuntu station.
2. pull the docker image "docker pull ingenieurmt/fuellock"
3. Then "docker run -d  -e API_KEY=YOUR_GOOGLE_API_KEY  -p 5000:5000 fuellock"

**Comment by MattKobayashi** [comment]
Hey @micyew, truthfully it's even simpler than that. Once you've got Docker installed on your Ubuntu instance (use the Docker-maintained PPA rather than the official repo version) you can run the following to get it working:

<pre>docker run -d \
  -e API_KEY=YOUR_GOOGLE_API_KEY \
  -p 5000:5000 \
  ingenieurmt/fuellock</pre>

Then browse to http://<Ubuntu host IP>:5000 and you should see the Fuel Locker login page. Let me know how you go!

**Comment by micyew** [comment]
@ingenieurmt pardon me a newbie question. What is the difference between PPA and official repo version? By official version, is it the one referring to "docker-ce"...PPA version is it "docker.io"? That's the info. I found from Googling...

**Comment by MattKobayashi** [comment]
No problem at all! When I say "official repo", I mean the default Ubuntu software repository. So instead of simply installing Docker immediately with APT, add the Docker PPA first then install with APT. More detailed instructions here: https://docs.docker.com/install/linux/docker-ce/ubuntu/

**Comment by micyew** [comment]
@ingenieurmt Sweet....Yes, get it running on docker now....easy peasy lemon squeezy!!!...cheers...

**Comment by freyta** [comment]
Hey all.

I've updated the Dockerfile to use python3-alpine now since I've ported it to Python3. Seems to work fine on my side, let me know if there's any issues!

**Comment by micyew** [comment]
Works fine....seems that python-alpine (v2 and v3) unable to support
pyopenssl...I try to use https in Flask and it requires pyopenssl..

**Comment by charleszlu** [comment]
@micyew I use a nginx reverse proxy in front with a let's encrypt certificate bot so it's a non issue. It's cleaner this way as well.

**Comment by micyew** [comment]
@charleszlu thanks....this is new to me..need to research a bit here...Is the nginx another docker container running in front of this 711 app? You have some good links that can start with?

**Comment by charleszlu** [comment]
@micyew Yes that's correct.
This is a good resource to get you started. I am using this setup but with a DNS challenge instead as I have to generate a wildcard certificate.
[https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71](url)

**Comment by charleszlu** [comment]
> Hey all.
> 
> I've updated the Dockerfile to use python3-alpine now since I've ported it to Python3. Seems to work fine on my side, let me know if there's any issues!

I just locked in some Fuel with the latest docker image and can confirm it works well.

**Comment by micyew** [comment]
Did you all notice the expire time show in the phone apps and the web apps
is a bit different?

**Comment by charleszlu** [comment]
The timezone on the web app is in UTC. 
@freyta Maybe we should make use of the TZ environment variable (and add tzdata package to the Dockerfile)

**Comment by MattKobayashi** [comment]
@micyew @charleszlu I'm working on trying to get the tzdata package working in the Docker image, so far it's been a bit tricky but I'll keep chipping away at it.

**Comment by charleszlu** [comment]
@ingenieurmt Oh it's not too hard I think. I have created a pull request #22 (also added bash).

**Comment by charleszlu** [comment]
@ingenieurmt Looks like the PR has been merged.
