### ISSUE TITLE
OSError: [Errno 8] Exec format error: '/app.py'

### ISSUE THREAD

**Issue by nickhhg** [freyta/7Eleven-Python#25]
Not sure if this is platform specific, but attempting to run the Docker image when built on Windows 10 results in the following error
`OSError: [Errno 8] Exec format error: '/app.py'`

**Traceback**
```
PS C:\repos\7Eleven-Python> docker run -p 5000:5000 test
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "app.py", line 600, in <module>
    app.run(host='0.0.0.0',debug=True)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 1007, in run_simple
    run_with_reloader(inner, extra_files, reloader_interval, reloader_type)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 332, in run_with_reloader
    sys.exit(reloader.restart_with_reloader())
  File "/usr/local/lib/python3.7/site-packages/werkzeug/_reloader.py", line 176, in restart_with_reloader
    exit_code = subprocess.call(args, env=new_environ, close_fds=False)
  File "/usr/local/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/app.py'
```

**Solution**
Some quick googles suggests this is a recent issue stemming from an updated library Flask uses.

One supposed fix is adding a shebang to app.py . This did not work for me, it resulted in a different error occurring
`#!/usr/bin/env python`

What did work was adding a chmod to Dockerfile, before ENTRYPOINT
`RUN chmod 644 app.py`

Permissions before chmod
`-rwxr-xr-x    1 root     root       26.0K May 27 10:48 app.py*`

Permissions after chmod
`-rw-r--r--    1 root     root       26.0K May 27 10:48 app.py`

**Comment by nickhhg** [comment]
Building on Windows does throw this warning, which I've had previously, but never seemingly had an issue until now
`SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.`

**Comment by freyta** [comment]
Try removing the debug=True part from app.run , see if that helps.

**Comment by nickhhg** [comment]
That seems to work as well

**Comment by freyta** [comment]
Should be fixed (again) in the newest push.
