### ISSUE TITLE
Timezone error on startup in BackgroundScheduler (Python 3.6 on Android)

### ISSUE THREAD

**Issue by deeevan** [freyta/7Eleven-Python#27]
Running script Qpython3 on Android which is python 3.6. Exits on startup with the below console output (note I renamed app.py to main.py to allow Qpython3 to execute it):
hon/projects3/autolock/main.py  && exit  <
Note: Opening stores.json
Traceback (most recent call last):
  File "/storage/emulated/0/qpython/projects3/autolock/main.py", line 454, in <module>
    scheduler = BackgroundScheduler()
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 126, in configure
    self._configure(config)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/data/user/0/org.qpython.qpy3/files/lib/python3.6/site-packages/tzlocal/unix.py", line 125, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
1|:/ $

It's resolved by specifying a timezone when instantiating BackgroundScheduler in app.py eg.
scheduler = BackgroundScheduler(timezone='UTC')

I'm not sure whether it's a python 3.6, apscheduler version or Qpython3 specific error

**Comment by MattKobayashi** [comment]
Same issue occurs if no TZ env variable is specified for the Docker container.

**Comment by deeevan** [comment]
I thought it might be an Android location permissions issue (not being able to get local timezone), but still occurs after reinstall and granting permission.

**Comment by freyta** [comment]
Okay how about this for fixing the error(s):

Changing lines 453 and 454 so it reads:
```
    # Start the autosearch scheduler
    if(functions.TZ in [None,""]):
        scheduler = BackgroundScheduler(timezone='UTC')
    else:
        scheduler = BackgroundScheduler(timezone=functions.TZ)
```

That way if a timezone **is** set it will use the one set by the environmental variable, otherwise default to UTC (I think we should use AEST though? Or at least an Australian timezone.

**Comment by deeevan** [comment]
Given the schedule is periodic not a set time of day, I don't think it matters what timezone is used. But yeah, why not pick an Australian timezone

**Comment by freyta** [comment]
Is this considered fixed yet? Also, how do you even get this running on QPython3? I tried to help someone on OzBargain yesterday and I'm knee deep in who knows what trying to figure it out! I could barely even install the requirements..

**Comment by deeevan** [comment]
Yes, this can be closed. As for Qpython3, I've been refining instructions 

1. Save Freighter's script to a folder in qpython/projects3 eg. yourFolder 
Next step is optional if you want to launch the project as a program, and not open app.py and hit Play
2. Rename app.py to main.py because Qpython3 looks for that name 
3. Launch the pip console in Qpython3 
Select 3 dots menu, then PIP Console
4. Install the required modules by typing:
pip3 install -r projects3/yourFolder/requirements.txt
5. Exit PIP Console and go back to the main screen
6. Launch the application
Select Projects, Programs then <yourFolder>
