### ISSUE TITLE
pycryptodome can not be installed on QPython/Android

### ISSUE THREAD

**Issue by deeevan** [freyta/7Eleven-Python#30]
Not an issue, just notification that 7Eleven-Python is no longer compatible with Android.
pycryptodome has C binaries, so pip3 install is failing in QPython.
Confirmed here: https://github.com/Legrandin/pycryptodome/issues/25

Maybe the encryption code in functions.py can be segregated/toggled off based on a user setting, but I won't have time for an in-depth look for awhile.

**Comment by Kirkzy** [comment]
pip3 install gcc
try above code before you install pycryptodome

**Comment by deeevan** [comment]
Nope. C binaries aren't happening on Android 

-->pip3 install gcc
Collecting gcc
  Could not find a version that satisfies the requirement gcc (from versions: )
No matching distribution found for gcc
-->

**Comment by GitHubJack1182** [comment]
Other module failing to install (probably also due to dependency on C binaries)
pyOpenSSL==18.0.0

**Comment by freyta** [comment]
Fixed.
- Changed the requirements.txt for android to `android_req.txt`.
- Now use pyDes instead of pycryptodome.
