### ISSUE TITLE
Error when login

### ISSUE THREAD

**Issue by tzheng-splunk** [freyta/7Eleven-Python#37]
Cannot login, get 302 error in log

172.17.0.1 - - [08/Sep/2019 07:30:44] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [08/Sep/2019 07:31:01] "POST /login HTTP/1.1" 302 -
172.17.0.1 - - [08/Sep/2019 07:31:03] "GET / HTTP/1.1" 200 -

**Comment by NGPriest** [comment]
302 isn't an error...
302 is a status code...

> The HTTP response status code 302 Found is a common way of performing URL redirection. The HTTP/1.0 specification (RFC 1945) initially defined this code, and gave it the description phrase "Moved Temporarily" rather than "Found".
>
> https://en.wikipedia.org/wiki/HTTP_302

**Comment by tzheng-splunk** [comment]
So what is the solution?

**Comment by NGPriest** [comment]
@tzheng-splunk I'm not sure, i don't even know what the problem is...

**Comment by freyta** [comment]
Explain what's happening. What's the actual error message? Give us more information and we may try and help you more

**Comment by NGPriest** [comment]
Should we close this issue? :S
