### ISSUE TITLE
Python version on Synology

### ISSUE THREAD

**Issue by hooray4p** [freyta/7Eleven-Python#42]
Hi guys,

Thanks for the awesome program. 
The code works perfectly fine on MacBook but it doesn't on Synology.
Currently, Synology has Python 3.5 as the latest option available. 
It does not correctly show locked details.

Can it be compatible with version 3.5?

**Comment by NGPriest** [comment]
If it ain't broke, don't fix it...

And keep using your MacBook...

**Comment by freyta** [comment]
I am using Docker on my Synology NAS to run the script. I would recommend using that, the image is relatively small (~350mb?) and takes up very little RAM.

You can read how to set it up using Docker in the main file, https://github.com/freyta/7Eleven-Python#docker-usage. Let me know if you need more help
