### ISSUE TITLE
[FEATURE] Using Reverse Proxy

### ISSUE THREAD

**Issue by beaudeanadams** [freyta/7Eleven-Python#47]
Would someone be interested in working with me to make the app reverse-proxy-able? 

At present, I'm finding Flask doesn't like when you use SSL on the endpoint.

**Comment by MattKobayashi** [comment]
Have you tried following the instructions here? https://github.com/freyta/7Eleven-Python/commit/ae826a9a3eabc43259afad3feb22d138df98bfd4

**Comment by beaudeanadams** [comment]
Yes and no. 
That approach is not desirable and/or possible when utilizing a docker container where you also have multiple services/containers coming in on 443/80 using a reverse proxy setup...

Ideally, you should be able to use a reverse proxy (i.e. Nginx) to go from whatever url you want (i.e. fuel.example.com) to the container and port (i.e. fuellock:5000) and the reverse proxy will handle all the certs...

**Comment by MattKobayashi** [comment]
> Ideally, you should be able to use a reverse proxy (i.e. Nginx) to go from whatever url you want (i.e. fuel.example.com) to the container and port (i.e. fuellock:5000) and the reverse proxy will handle all the certs...

Indeed, and this is the approach I use and recommend (using [Nginx Proxy Manager](https://github.com/jc21/nginx-proxy-manager)).

**Comment by beaudeanadams** [comment]
Mine won’t work using NGINX proxy manager. Is that modifying app.py?

**Comment by MattKobayashi** [comment]
Nope, not at all. Simply have Nginx Proxy Manager running in the same Docker network as 7Eleven-Python, point your Destination to http://[containername]:5000 and configure your external stuff as you want it.

Note that you don't need HTTPS internally between Nginx Proxy Manager and 7Eleven-Python as it's not even leaving the internal Docker network, let alone traversing the internet. If you're really concerned/paranoid, you can have Nginx Proxy Manager and 7Eleven-Python on their own Docker network for complete isolation.

**Comment by beaudeanadams** [comment]
> Nope, not at all. Simply have Nginx Proxy Manager running in the same Docker network as 7Eleven-Python, point your Destination to http://[containername]:5000 and configure your external stuff as you want it.

Hmm.. I tried that and I'm getting '502 - Bad Gateway' and the following in the 7Eleven-Python log:
https://imgur.com/a/CeSFm76

*edit, unicode encoding was killing the log

**Comment by beaudeanadams** [comment]
Looks like it was an issue with my instance of Nginx Proxy Manager...
Thank you @ingenieurmt for your help!
