### ISSUE TITLE
It is broken now.

### ISSUE THREAD

**Issue by deamen** [freyta/7Eleven-Python#51]
The returnHeaders:
```
["{'Date': 'Sun, 26 Jan 2020 08:15:17 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '70', 'Connection': 'keep-alive', 'Cache-Control': 'no-cache', 'Pragma': 'no-cache', 'Expires': '-1', 'Server': 'Microsoft-IIS/10.0', 'X-AspNet-Version': '4.0.30319', 'X-Powered-By': 'ASP.NET'}"]
```
The returnContent:
```
{
  "Message": "An unknown error occurred. Please try again later"
}
```
The app still works.

Could it be API change on the 711 end?

**Comment by freyta** [comment]
Mine works, I can login perfectly fine..

Are you running the latest code?

**Comment by deamen** [comment]
Yeah, just cloned and built the docker image. 
Maybe it's ISP related? I will give it a try again on Tuesday in my VPS.
I was worried there might be an API change. Will report back.

**Comment by freyta** [comment]
Perhaps. What is the error message that comes up if there is one?

**Comment by deamen** [comment]
After I clicked the login button, I got the error message:
```
Oops, error:
An unknown error occurred. Please try again later
```
Didn't get time to try it in my VPS. Will definitely try it tomorrow.

**Comment by deamen** [comment]
I think this is ISP related, the same docker image just doesn't work on my home network.
I am using TPG FTTN, there shouldn't be a lot of people using it.
