### ISSUE TITLE
Connection error to host='711-goodcall.api.tigerspike.com', port=443, can not start service

### ISSUE THREAD

**Issue by zunreal** [freyta/7Eleven-Python#52]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='711-goodcall.api.tigerspike.com', port=443): Max retries exceeded with url: /api/v1/store/StoresAfterDateTime/1001 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5b765fa350>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by manishjainin** [comment]
Facing the same issue. Looks like 7 eleven has changed their end-point for the fuel lock.

**Comment by rajeshsub** [comment]
This seems to have resolved itself now.

**Comment by freyta** [comment]
It is because the app itself was down. Perhaps it shows an error message if
you use the app that we need to replicate

**Comment by MattKobayashi** [comment]
It looks like 7-Eleven might be preparing to migrate their API endpoint:

```fuel          | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='711-goodcall.api.tigerspike.com', port=443): Max retries exceeded with url: /api/v1/account/login (Caused by SSLError(SSLCertVerificationError("hostname '711-goodcall.api.tigerspike.com' doesn't match 'apps.7eleven.com.au'")))```

I've got a hotfix ready to go for this if they do finalise the changes, but if it happens in the meantime, simply edit the BASE_URL variable in settings.py to "https://apps.7eleven.com.au/api/v1".

**Comment by freyta** [comment]
App was just down. All is working now.
