### ISSUE TITLE
auto locker only premium 98?

### ISSUE THREAD

**Issue by lowgoz** [freyta/7Eleven-Python#54]
<3 this repo. Well done! 

I just can't find where to enable to auto lock in for e10 instead of it defaulting to trying to auto lock in premium in the settings?

**Comment by wheeliekegman** [comment]
Thanks for this project. I also have never seen anything like it.

I also have the same issue. I open the python app.py and it locks in premium 98.

I think i have opened every file in the rep to see if I can edit to Diesel, but I can't seem to find out the right place?

I'd love some help...tia

**Comment by freyta** [comment]
Hey. 
Sorry for being horrible at replying, life's got in the way and I haven't got much motivation to work on programming stuff.

I've hard coded the fuel type on line 206 of the autolocker.py. Link -> https://github.com/freyta/7Eleven-Python/blob/master/autolocker.py#L206

In one of the files (functions.py I think) near the top it says which fuel type is which.

Edit: I found it:

 
```
52 = Unleaded 91
53 = Diesel
54 = LPG
55 = Unleaded 95
56 = Unleaded 98
57 = E10
```
So in the mean time you can replace the number 56 in the autolocker with the fuel type you want until I add the option.

**Comment by wheeliekegman** [comment]
Thanks so much - I'll have a play with the code....I'll have to go and buy 2 litres (or whatever the min is!) of 98 to get rid of my current locked price. Then Lets hope Diesel is locked! 
Appreciate your reply - Def understand life getting in the way!

**Comment by lowgoz** [comment]
> Hey.
> Sorry for being horrible at replying, life's got in the way and I haven't got much motivation to work on programming stuff.
> 
> I've hard coded the fuel type on line 206 of the autolocker.py. Link -> https://github.com/freyta/7Eleven-Python/blob/master/autolocker.py#L206
> 
> In one of the files (functions.py I think) near the top it says which fuel type is which.
> 
> Edit: I found it:
> 
> ```
> 52 = Unleaded 91
> 53 = Diesel
> 54 = LPG
> 55 = Unleaded 95
> 56 = Unleaded 98
> 57 = E10
> ```
> 
> So in the mean time you can replace the number 56 in the autolocker with the fuel type you want until I add the option.

Keep being awesome dude. Love your work.

**Comment by freyta** [comment]
Hey mate.

A bit late to the party of updating code, but I've just pushed through an update. It should work!

https://github.com/freyta/7Eleven-Python/commit/e50cf585fd5f21e2c8f5070f3c5c6ec4d0c77048
