### ISSUE TITLE
the app doesn't get published to any Docker registry

### ISSUE THREAD

**Issue by SongGithub** [freyta/7Eleven-Python#55]
the app Docker image doesn't get published to any Docker registry. It would be a better user experience if users can simply use `Docker run <a image from Dockerhub> `

I am happy to work with the maintainers to setup a CD pipeline & a Docker hub repo that can deliveryDocker image to the Dockerhub.

**Comment by MattKobayashi** [comment]
Hey @SongGithub, I do maintain images in my personal Docker Hub repo, you're more than welcome to pull them from https://hub.docker.com/repository/docker/ingenieurmt/fuel. I've been meaning to get a CD pipeline going for my images but haven't had time as yet.

**Comment by SongGithub** [comment]
I think it maybe good to use this repo and @freyta Dockerhub repo as the 1st choice, rather than using contributor's Dockerhub. This will help the community more, as it is the default repo for the project that is most likely to be found on the Internet.

**Comment by SongGithub** [comment]
I have implemented a CD pipeline with CircleCI. The pipeline publishes Docker image to a repo in Dockerhub. 

Please the project maintainers let me know if you are interested. If so, I can make a PR to contribute back.

**Comment by freyta** [comment]
Hey. I'm not sure what a CD pipeline is, care to explain it simply for me?

Cheers

**Comment by SongGithub** [comment]
hi @freyta , I mean a continuous deploy pipeline. 

The pipeline will build&publish docker images to public Dockerhub. The published image will make it easier for users to consume, because they don't need to access Github and build docker image.

The easier to use, the better adoption.

**Comment by freyta** [comment]
Ok, well you can happily push through a pull request.

**Comment by calvinbui** [comment]
@freyta you'll have to enable them yourself as it creates webhooks to the repo

https://docs.docker.com/docker-hub/builds/

**Comment by SongGithub** [comment]
hi @calvinbui , how about using a CI service instead of Dockerhub to build Docker image?  This way every component does one thing and does it well.

**Comment by calvinbui** [comment]
No matter what build tool is used, the image will need to be hosted _somewhere_ and some sort of authentication/credentials will be required to push the image to the chosen registry. 

Why not kill two birds with one stone and use Docker Hub? The build process for this image is as simple as it gets.

**Comment by freyta** [comment]
Ok, I think I have solved this. https://hub.docker.com/r/freyta/7eleven-python .

**Comment by calvinbui** [comment]
> Ok, I think I have solved this. https://hub.docker.com/r/freyta/7eleven-python .

working!

**Comment by freyta** [comment]
Marking as closed since it is working

**Comment by SongGithub** [comment]
good to hear that @freyta . 

btw, in Dockerhub page, there are 2 things could be improved: 
- there is no need to instruct how to build image in dockerhub.
- in docker run command instruction, image name should be updated to a valid dockerhub image name. `freyta/7Eleven-Python`, rather than `fuellock`

also, README file needs to be updated accordingly too.
