### ISSUE TITLE
New Version of 7 Eleven App release no longer requires credit to lock in

### ISSUE THREAD

**Issue by hikaru78** [freyta/7Eleven-Python#57]
I assume will require an update? 

i got it running a bit dirty
settings py change app version to 1.10.0

app.py changed 
NumberOfLitres = int(float(session['cardBalance']) / session['LockinPrice'] * 100)
to NumberOfLitres = int(100)
im sure not ideal but it works until someone smarter than me fixes it properly

**Comment by lowgoz** [comment]
still getting

```
Oops, error:
Please upgrade to enjoy an easier way to lock in our best local fuel price
Refresh 
```

**Comment by beaudeanadams** [comment]
I've applied this on my fork and have submitted a PR for @freyta :)

**Comment by hikaru78** [comment]
> still getting
> 
> ```
> Oops, error:
> Please upgrade to enjoy an easier way to lock in our best local fuel price
> Refresh 
> ```
Did you update line 54 of settings.py to the new app version?

**Comment by MattKobayashi** [comment]
@lowgoz You'll need to ensure any references to the APP_VERSION have been updated to 1.10.2000 or 1.10.2044, otherwise you'll continue to see that error when you log in.

**Comment by hikaru78** [comment]
I'd update the integer value for litres in app.py to 150 as well.  The new
app version seems to do 150 by default so any locking that isn't 150 is
gonna stand out

**Comment by lowgoz** [comment]
> > still getting
> > ```
> > Oops, error:
> > Please upgrade to enjoy an easier way to lock in our best local fuel price
> > Refresh 
> > ```
> 
> Did you update line 54 of settings.py to the new app version?

no lol

**Comment by PrawnMan** [comment]
I just built the docker image from source, im also getting the same "Please upgrade to enjoy an easier way to lock in our best local fuel price" error.

**Comment by Motordom** [comment]
@PrawnMan have you made sure that you're not grabbing an older build docker image when running?

Try deleting all your images for fuellock and rebuilding

**Comment by PrawnMan** [comment]
> @PrawnMan have you made sure that you're not grabbing an older build docker image when running?
> 
> Try deleting all your images for fuellock and rebuilding


Hey thanks! I had to wrestle with docker and prune a bunch of things for half an hour, but deleting the  old images and redoing the containers resolved it for me!

**Comment by Motordom** [comment]
@freyta this issue is now resolved, can we close?
