### ISSUE TITLE
unable to lock in price with a new account

### ISSUE THREAD

**Issue by showdownhero** [freyta/7Eleven-Python#76]
Hi guys,

I've just created a 7Eleven account in order to lock in fuel pricing. However when I log in none of the "Automatic", "Manual" or "Settings" links are active.

As you can see from the screen shot I don't have an account balance (not sure if this matters). Also I have never locked in fuel on this account before.

![image](https://user-images.githubusercontent.com/62083937/82197519-75b46480-993e-11ea-8eb2-4f37c697730a.png)

**Comment by MattKobayashi** [comment]
Hi @showdownhero, have you tried disabling any extensions or plugins you have in your web browser? It could be that something is blocking the links from functioning.

**Comment by showdownhero** [comment]
> Hi @showdownhero, have you tried disabling any extensions or plugins you have in your web browser? It could be that something is blocking the links from functioning.

Hey mate, I've tried with multiple different browsers and in private mode (with all extensions blocked) to no avail. Here's a screen shot from Firefox with all extensions blocked

![image](https://user-images.githubusercontent.com/62083937/82205401-e745e000-9949-11ea-8d5e-02d82ccfa316.png)

**Comment by showdownhero** [comment]
I made a second account with a separate email address where I was able to lock in the price from the app on my phone, which correctly displays on the webpage and it also displays the settings to setup an autolock.

![image](https://user-images.githubusercontent.com/62083937/82207887-e747df00-994d-11ea-8fdf-26e40ffc0b78.png)

**Comment by MattKobayashi** [comment]
@showdownhero Thanks for the further info! A couple more questions if I may:

- Are you using Docker or just running the app standalone with a Python interpreter? If not Docker:

  - What version of Python are you using?
  - Have you installed all the dependencies using the requirements.txt file?

**Comment by showdownhero** [comment]
@ingenieurmt Thanks for all your help so far.

I'm just running standalone with Python.
Version is Python 3.8.2

I ran the pip install -r requirements.txt when I set everything up but I ran it again just to make sure there weren't any errors with the initial install and this was command prompt looked like. Everything just showed as "Requirement already satisfied"

![image](https://user-images.githubusercontent.com/62083937/82213303-452cf480-9957-11ea-8b00-04f9df04c223.png)

**Comment by freyta** [comment]
Hey mate.
Have you activated the account? And it looks like you (correctly) used `pip3 install -r requirements.txt`, otherwise you couldn't log in with another account.

**Comment by showdownhero** [comment]
> Hey mate.
> Have you activated the account? And it looks like you (correctly) used `pip3 install -r requirements.txt`, otherwise you couldn't log in with another account.

Hey mate, yeah the account is definitely activated. I can use the app on my iphone and log in with both accounts I created (they don't let you log in until the account is activated via the email link).

**Comment by freyta** [comment]
Ok. Did you get it to work? You have JavaScript enabled don't you?
If it still doesn't work I will hopefully be able to help debug it this arvo?

**Comment by freyta** [comment]
An update: I solved the issue. I was getting ready to push the changes along with a few minor small ones, when I goofed up and deleted it the other stuff I wanted. I'll push it through tomorrow or the day after.

**Comment by showdownhero** [comment]
@freyta legend

**Comment by freyta** [comment]
Okay, this _should_ be fixed. Turns out I luckily still had my browser open and I could recover what I wanted to update.

**Comment by showdownhero** [comment]
@freyta working now :) thanks so much for the fix

![image](https://user-images.githubusercontent.com/62083937/82535481-4003bb80-9b8a-11ea-9233-aa26d65999de.png)
