### ISSUE TITLE
[Security update(?)] Account Null

### ISSUE THREAD

**Issue by Venomish-Snake** [freyta/7Eleven-Python#78]
Hi, i'd like to thank the devs and supporters of this script.

I believe theres some kind of bug where your account nulls when using this script. 
After successfully using the voucher, my app still says i got a voucher active (it was the same voucher as the one i scanned). It's been a few hours since i scanned the voucher and it seems like it isnt going away (unless i leave it to expire in 7 days, i'd imagine itll go).

Im pretty sure it may be a 711 error; but can i get a confirmation? 

Thanks :)

**Comment by andyrb412** [comment]
Is the voucher still showing up in the 7/11 app or just in the web script?

I ask because I've experienced the same issue a few times recently; the voucher has disappeared immediately from the app but remained in the web script.

A simple fix was to log out of the script and back in.  Try that?

**Comment by Venomish-Snake** [comment]
Since then i've logged out of the account and created a new one, before i logged out i did try to use the script to lock in a new price but it wouldnt let me log in. It would just display an error.

I've tried to log in the app, and it shows me an error. (I assume it was the same error showing on my pc)
![image](https://user-images.githubusercontent.com/42530045/82780503-bb22e580-9e9a-11ea-9fe5-e49d6a795ed5.png)

**Comment by freyta** [comment]
So the voucher still shows up in the web script? That's odd. Perhaps their server hasn't updated.
Have you been able to reproduce the error? I don't fully understand what is happening.

**Comment by Venomish-Snake** [comment]
So essentially, I had already had my account logged in on my mobile device and locked in a voucher using the web script. The voucher did work at the register and the fuel discount was applied, however, the voucher was still active on my phone (it had the same code under the bar code). Thus, I was unable to lock in a price again on my mobile device.
I thought it may have been an issue with my mobile device, so i logged out of the account and attempted to log in with your webscript, however, there was an error and i could not log in. The comment I posted above is what happens when I try logging in that same account on my mobile device. 

Update: Currently, i am able to log in the account on both, the phone app and web app. However, the same voucher i scanned is still active on my account. Perhaps there was a bug with their system which scanned my voucher and deducted the price, but did not actually redeem my code?

**Comment by Venomish-Snake** [comment]
Ok so i can confirm that it was an issue with the 711 servers (or the attendant), i re scanned my voucher and it was accepted. :)
