### ISSUE TITLE
Running with Python3

### ISSUE THREAD

**Issue by micyew** [freyta/7Eleven-Python#8]
Hi,

Would like to know how do I run with with Python3? A lots of hash bytes/unicode error when I run with Python3. Any chances of converting it to Python3?

**Comment by freyta** [comment]
Hey mate.
To run it with Python3 it needs to have a few changes made. I'll get around to updating it hopefully soon but it's in the pipeline for sure!

**Comment by maxpower010** [comment]
Hi @micyew,

I forked freytas repo a while back and got it running on Python3

[7Eleven-Python3](https://github.com/maxpower010/7Eleven-Python)

not updated with the latest changes though.

**Comment by micyew** [comment]
Hmm..See like something change at the 711 Eleven backend....Can't login
even with Python2 code......

**Comment by freyta** [comment]
@micyew, yep, they've made changes to the backend. look here at issue #18

**Comment by micyew** [comment]
I see...some encryption changes...hopefully will work out something...

**Comment by micyew** [comment]
But strange is the Android 711 app still version 1.7.1 and it can
login...how can backend change without an app update?

**Comment by freyta** [comment]
The magic of computers!

The generateTssa function works perfectly fine in the other issue for a temporary fix

**Comment by freyta** [comment]
Done. Code is now using Python3.
